name: Scheduled Node.js CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # 添加这行以允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # 设置作业超时时间为10分钟

    strategy:
      matrix:
        node-version: [20.x] 

    steps:
      - uses: actions/checkout@v3 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install 
      - name: Run a script
        run: node main.js 
      - name: Commit Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Update files at $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
